[package]
name = "stream-cancel"
version = "0.4.4"

description = "A library for interrupting asynchronous streams."
readme = "README.md"

authors = ["Jon Gjengset <jon@thesquareplanet.com>"]

homepage = "https://github.com/jonhoo/stream-cancel"
repository = "https://github.com/jonhoo/stream-cancel.git"

keywords = ["asynchronous", "futures"]
categories = ["network-programming", "asynchronous"]

license = "MIT/Apache-2.0"

[badges]
travis-ci = { repository = "jonhoo/stream-cancel" }
maintenance = { status = "passively-maintained" }

[dependencies]
futures = "0.1"

[dev-dependencies]
tokio = "0.1"
